repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.20.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "modules", "-recursive"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    - id: no-commit-to-branch

    # Detect hardcoded secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.26.0
    hooks:
    - id: gitleaks

    # Bash
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
    - id: shfmt
      args:
      - -l
      - -i
      - '2'
      - -ci
      - -sr
      - -w
    - id: shellcheck
