formatter: markdown table

recursive:
  enabled: true
  path: modules
  include-main: false

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  hide-empty: true

sections:
  show:
    - header
    - inputs
    - outputs
    - providers
    - resources
    - modules
