name: Terraform Preview

on:
  workflow_dispatch:
  push:
    branches:
      - feature/*
env:
  AWS_REGION: "us-east-1"
  TF_WORKSPACE: "dev"

defaults:
  run:
    shell: bash

jobs:
  Preview:
    name: Plan Terraform changes stacks
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Terramate
        uses: terramate-io/terramate-action@v2
        with:
          version: "0.13.0"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1
          terraform_wrapper: false

      - name: Check Terramate formatting
        run: terramate fmt --check --changed
        continue-on-error: true

      - name: List changed stacks
        id: list
        run: terramate list --changed

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::471112559300:role/terraform

      - name: Initialize Terraform in changed stacks
        if: steps.list.outputs.stdout
        id: init
        run: |
          terramate run \
            --parallel 1 \
            --changed \
            -- \
            terraform init -lock-timeout=5m
        env:
          TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
#          GITHUB_TOKEN: ${{ github.token }}

      - name: Validate Terraform configuration in changed stacks
        if: steps.list.outputs.stdout
        id: validate
        run: |
          terramate run \
            --parallel 5 \
            --changed \
            --mock-on-fail \
            --enable-sharing \
            -- \
            terraform validate

      - name: Plan Terraform changes in changed stacks
        if: steps.list.outputs.stdout
        id: plan
        max_attempts: 2
        retry_wait_seconds: 5
        run: |
          terramate run \
            --parallel 5 \
            --changed \
            --enable-sharing \
            --mock-on-fail \
            --continue-on-error \
            -- \
            terraform plan -out out.tfplan -lock=false

      - name: Apply Terraform changes stacks
        if: steps.plan.outcome == 'success'
        max_attempts: 2
        retry_wait_seconds: 5
        run: |
          terramate run \
            --parallel 5 \
            --changed \
            --enable-sharing \
            --mock-on-fail \
            -- terraform apply -auto-approve
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#          TF_WORKSPACE: ${{ env.TF_WORKSPACE }}