name: Terraform Preview

on:
  pull_request:

env:
  AWS_REGION: us-east-1
  TF_WORKSPACE: dev
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

defaults:
  run:
    shell: bash

jobs:
  preview:
    name: Plan Terraform changes in changed Terramate stacks
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: read

    steps:
      - name: Prepare pull request preview comment
        if: github.event.pull_request
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: preview
          message: |
            ## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}

            :warning: preview is being created... please stand by!

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Terramate
        uses: terramate-io/terramate-action@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1
          terraform_wrapper: false

      - name: Check Terramate formatting
        run: terramate fmt --check

      - name: Check Terraform formatting
        run: terraform fmt -recursive -check -diff

      - name: List changed stacks
        id: list
        run: terramate list --changed

      ## Comment this step out if not using AWS
      - name: Configure AWS credentials via OIDC
        if: steps.list.outputs.stdout
        id: auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::975050361443:role/github

      - name: Initialize Terraform in changed stacks
        if: steps.list.outputs.stdout
        id: init
        run: |
          terramate run \
            --parallel 1 \
            --changed \
            -- \
            terraform init -lock-timeout=5m

      - name: Validate Terraform configuration in changed stacks
        if: steps.list.outputs.stdout
        id: validate
        run: |
          terramate run \
            --parallel 5 \
            --changed \
            -- \
            terraform validate

      - name: Plan Terraform changes in changed stacks
        if: steps.list.outputs.stdout
        id: plan
        run: |
          terramate run \
            --parallel 5 \
            --changed \
            --enable-sharing \
            --mock-on-fail \
            --continue-on-error \
            -- \
            terraform plan -out out.tfplan -lock=false

      ## Note: Due to a limitation in the size of a GitHub PR comment (65,536 characters), we are truncating the output if it's too long. For better and complete previews or changes consider Terramate Cloud.
      ## Note: Depending on the setup, you may need to add pr-comment.txt to your .gitignore to avoid any failures
      - name: Generate preview details
        if: steps.list.outputs.stdout
        id: comment
        run: |
          echo >>pr-comment.txt "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
          echo >>pr-comment.txt
          echo >>pr-comment.txt "### Changed Stacks"
          echo >>pr-comment.txt
          echo >>pr-comment.txt '```bash'
          echo >>pr-comment.txt "${{ steps.list.outputs.stdout }}"
          echo >>pr-comment.txt '```'
          echo >>pr-comment.txt
          echo >>pr-comment.txt "#### Terraform Plan"
          echo >>pr-comment.txt
          echo >>pr-comment.txt '```terraform'
          terramate run --changed -- terraform show -no-color out.tfplan |& dd bs=1024 count=248 >>pr-comment.txt
          [ "${PIPESTATUS[0]}" == "141" ] && sed -i 's/#### Terraform Plan/#### :warning: Terraform Plan truncated: please check console output :warning:/' pr-comment.txt
          echo >>pr-comment.txt '```'
          cat pr-comment.txt >>$GITHUB_STEP_SUMMARY

      - name: Generate preview when no stacks changed
        if: success() && !steps.list.outputs.stdout
        run: |
          echo >>pr-comment.txt "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
          echo >>pr-comment.txt
          echo >>pr-comment.txt "### Changed Stacks"
          echo >>pr-comment.txt
          echo >>pr-comment.txt 'No changed stacks, no detailed preview will be generated.'
          cat pr-comment.txt >>$GITHUB_STEP_SUMMARY

      - name: Generate preview when things failed
        if: always() && failure()
        run: |
          echo >>pr-comment.txt "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
          echo >>pr-comment.txt
          echo >>pr-comment.txt "### Changed Stacks"
          echo >>pr-comment.txt
          echo >>pr-comment.txt '```bash'
          echo >>pr-comment.txt "${{ steps.list.outputs.stdout }}"
          echo >>pr-comment.txt '```'
          echo >>pr-comment.txt ':boom: Generating preview failed. Please see details in Actions output.'
          cat pr-comment.txt >>$GITHUB_STEP_SUMMARY

      - name: Publish generated preview as GitHub commnent
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: preview
          path: pr-comment.txt


#name: Terraform Preview
#
#on:
#  pull_request:
#
#env:
#  AWS_REGION: us-east-1
#  TF_WORKSPACE: dev
#  TF_IN_AUTOMATION: true
#  TF_INPUT: false
#  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
#
#defaults:
#  run:
#    shell: bash
#
#jobs:
#  Preview:
#    name: Plan Terraform changes stacks
#    runs-on: ubuntu-latest
#
#    permissions:
#      id-token: write
#      contents: read
#      pull-requests: write
#      checks: read
#
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v4
#      with:
#        ref: ${{ github.head_ref }}
#        fetch-depth: 0
#
#    - name: Restore Terraform plugin cache
#      uses: actions/cache@v4
#      with:
#        path: .terraform.d/plugin-cache
#        key: terraform-plugin-cache-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
#        restore-keys: |
#          terraform-plugin-cache-${{ runner.os }}-
#
#    - name: Istall tolls
#      uses: asdf-vm/actions/setup@v4
#
#    - name: Setup Tools
#      run: |
#        asdf plugin add terraform
#        asdf plugin add terramate
#        asdf install terraform
#        asdf install terramate
#
#    - name: Check Terraform formatting
#      run: terraform fmt -recursive -check -diff
#      continue-on-error: true
#      env:
#        TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
#        TF_IN_AUTOMATION: true
#        TF_INPUT: false
#        TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
#
#    - name: List changed stacks
#      id: list
#      run: terramate list --changed
#
#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v4
#      with:
#        aws-region: ${{ env.AWS_REGION }}
#        role-to-assume: arn:aws:iam::975050361443:role/github
#
#    - name: Initialize Terraform in changed stacks
#      if: steps.list.outputs.stdout
#      id: init
#      run: |
#        terramate run \
#          --parallel 1 \
#          --changed \
#          -- \
#          terraform init -lock-timeout=5m
#      env:
#        TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
#        TF_IN_AUTOMATION: true
#        TF_INPUT: false
#        TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
#
#    - name: Validate Terraform configuration in changed stacks
#      if: steps.list.outputs.stdout
#      id: validate
#      run: |
#        terramate run \
#          --parallel 5 \
#          --changed \
#          -- \
#          terraform validate
#
#    - name: Plan Terraform changes in changed stacks
#      if: steps.list.outputs.stdout
#      id: plan
#      run: |
#        terramate run \
#          --parallel 5 \
#          --changed \
#          --enable-sharing \
#          --mock-on-fail \
#          --continue-on-error \
#          -- \
#          terraform plan -out out.tfplan -lock=false
#
#    - name: Generate preview details
#      if: steps.list.outputs.stdout
#      id: comment
#      run: |
#        echo >>pr-comment.txt "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
#        echo >>pr-comment.txt
#        echo >>pr-comment.txt "### Changed Stacks"
#        echo >>pr-comment.txt
#        echo >>pr-comment.txt '```bash'
#        echo >>pr-comment.txt "${{ steps.list.outputs.stdout }}"
#        echo >>pr-comment.txt '```'
#        echo >>pr-comment.txt
#        echo >>pr-comment.txt "#### Terraform Plan"
#        echo >>pr-comment.txt
#        echo >>pr-comment.txt '```terraform'
#        terramate run --changed -- terraform show -no-color out.tfplan |& dd bs=1024 count=248 >>pr-comment.txt
#        [ "${PIPESTATUS[0]}" == "141" ] && sed -i 's/#### Terraform Plan/#### :warning: Terraform Plan truncated: please check console output :warning:/' pr-comment.txt
#        echo >>pr-comment.txt '```'
#        cat pr-comment.txt >>$GITHUB_STEP_SUMMARY
#
#    - name: Generate preview when no stacks changed
#      if: success() && !steps.list.outputs.stdout
#      run: |
#        echo >>pr-comment.txt "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
#        echo >>pr-comment.txt
#        echo >>pr-comment.txt "### Changed Stacks"
#        echo >>pr-comment.txt
#        echo >>pr-comment.txt 'No changed stacks, no detailed preview will be generated.'
#        cat pr-comment.txt >>$GITHUB_STEP_SUMMARY
#
#    - name: Generate preview when things failed
#      if: always() && failure()
#      run: |
#        echo >>pr-comment.txt "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
#        echo >>pr-comment.txt
#        echo >>pr-comment.txt "### Changed Stacks"
#        echo >>pr-comment.txt
#        echo >>pr-comment.txt '```bash'
#        echo >>pr-comment.txt "${{ steps.list.outputs.stdout }}"
#        echo >>pr-comment.txt '```'
#        echo >>pr-comment.txt ':boom: Generating preview failed. Please see details in Actions output.'
#        cat pr-comment.txt >>$GITHUB_STEP_SUMMARY
#
#    - name: Publish generated preview as GitHub commnent
#      uses: marocchino/sticky-pull-request-comment@v2
#      with:
#        header: preview
#        path: pr-comment.txt
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
