name: Generate Terraform Docs
on:
 pull_request:
   paths:
     - 'stacks/terraform/**/*.tf'
     - '.github/workflows/tfdocs.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup Tools
      uses: asdf-vm/actions/setup@v4
      commands: |
        terraform-docs --version
        terramate --version
        terraform --version
      


    - name: Terraform Docs
      id: tfdocs
      run: |
        terramate list -c | while read -r d; do
            if ls "$d"/*.tf >/dev/null 2>&1; then
              echo "Gerando docs em $d"
              terraform-docs markdown table "$d" > "$d/README.md"
            fi
          done
