name: Generate Terraform Docs
on:
- pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup Tools
    - uses: asdf-vm/actions/setup@v4

    - name: Terraform Docs
      id: tfdocs
      run: |
        terramate list -c | while read -r d; do
        echo "Gerando docs em $d"
        terraform-docs markdown table -c .terraform-doc.yml "$d" > "$d/README.md"
        done
